# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: txtNation SMSC HLR API HTTP Code Samples

# Short description (goes below the title; it will also be used in the RSS feed)
description: View and embed txtNation's SMSC HLR API HTTP Code Samples

# Your name, as you want it to appear underneath each post and in the footer
author: txtNation

# Your email if you want it to be linked on the contact page
author_email: sales@txtnation.com

#### Under the Hood Stuff #####

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# set code directory
code_dir: samples